// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMXcgbN5YENQzeoOX-IEHboWNLPP816I',
    appId: '1:648448478889:web:b27690ea97a76f6b8ca3b8',
    messagingSenderId: '648448478889',
    projectId: 'test-1bff8',
    authDomain: 'test-1bff8.firebaseapp.com',
    storageBucket: 'test-1bff8.firebasestorage.app',
    measurementId: 'G-1KRR2R5M0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUGXJwgMCXsdg8VYTLCDbY5iKEMQCc9M',
    appId: '1:648448478889:android:25ba33f3b07044638ca3b8',
    messagingSenderId: '648448478889',
    projectId: 'test-1bff8',
    storageBucket: 'test-1bff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzdqPu7PYpCJKw74RxQpJaiN5Ln6NWOJw',
    appId: '1:648448478889:ios:22e14bd18b5588b88ca3b8',
    messagingSenderId: '648448478889',
    projectId: 'test-1bff8',
    storageBucket: 'test-1bff8.firebasestorage.app',
    iosBundleId: 'com.example.flutterloginfirebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzdqPu7PYpCJKw74RxQpJaiN5Ln6NWOJw',
    appId: '1:648448478889:ios:22e14bd18b5588b88ca3b8',
    messagingSenderId: '648448478889',
    projectId: 'test-1bff8',
    storageBucket: 'test-1bff8.firebasestorage.app',
    iosBundleId: 'com.example.flutterloginfirebaseauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMXcgbN5YENQzeoOX-IEHboWNLPP816I',
    appId: '1:648448478889:web:57e9378f54b7ebc78ca3b8',
    messagingSenderId: '648448478889',
    projectId: 'test-1bff8',
    authDomain: 'test-1bff8.firebaseapp.com',
    storageBucket: 'test-1bff8.firebasestorage.app',
    measurementId: 'G-DPD0KG8X32',
  );

}